<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CandyKingdom.MarcyCms</RootNamespace>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageVersion Condition="'$(PackageVersion)' == ''">$(Version)</PackageVersion>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Ulmer-Morozov Dmitrii</Authors>
    <Company>Company Name</Company>
    <Product>Product Name</Product>
  </PropertyGroup>

  <PropertyGroup>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <WarningsAsErrors>;NU1605;CS8625;CS8618;</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\marcy\CandyKingdom.Marcy.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.0" />
  </ItemGroup>

</Project>
