name: Publish Package to NuGet
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@master
    - uses: nuget/setup-nuget@v2
      with:
        nuget-api-key: ${{ secrets.NuGetAPIKey }}
        nuget-version: '5.x'
        run: nuget restore CandyKingdom.sln
